window.BNM=window.BNM||{};BNM.gaming=(function(){let selected=null,current=null;
function open(){BNM.track("gaming_open");BNM.show("gaming");draw();gamingResult.innerHTML="";gamingToolbar.classList.add("hidden");gamingAll.classList.add("hidden")}
function draw(){gamePicker.innerHTML="";Object.entries(BNM_GAME_CHALLENGES).forEach(([id,g])=>{let b=document.createElement("button");b.className="game-tile"+(selected===id?" active":"");b.innerHTML=`<span>${g.emoji}</span><strong>${g.name}</strong><small>${g.challenges.length} challenges</small>`;b.onclick=()=>{selected=id;draw();gamingToolbar.classList.remove("hidden");gamingAll.classList.add("hidden");generate()};gamePicker.appendChild(b)})}
function renderCard(c,g,compact=false){return `<article class="panel game-card${compact?" compact-game-card":""}"><div class="eyebrow">${g.emoji} ${g.name} challenge</div><h2>${c.title}</h2><p class="challenge-brief">${c.brief}</p><div class="bonus-box"><small>🔥 BONUS</small><strong>${c.bonus}</strong></div><div class="card-actions"><button class="btn btn-primary accept-game-btn">Accept challenge →</button><button class="btn btn-ghost details-game-btn">More details</button>${compact?"":`<button class="btn btn-ghost another-game-btn">Give us another</button>`}</div><div class="challenge-details hidden"><div class="challenge-detail-block"><h4>How it works</h4><ol>${c.rules.map(r=>`<li>${r}</li>`).join("")}</ol></div><div class="challenge-detail-grid"><div><small>WHY IT'S FUN</small><p>${c.why}</p></div><div><small>QUICK TIP</small><p>${c.tip}</p></div></div></div></article>`}
function wire(container,c,g,compact=false){const accept=container.querySelector(".accept-game-btn"),details=container.querySelector(".details-game-btn"),detailBox=container.querySelector(".challenge-details"),another=container.querySelector(".another-game-btn");accept.onclick=()=>BNM.adventure.start({id:"game-"+selected+"-"+c.title.toLowerCase().replace(/[^a-z0-9]+/g,"-"),name:c.title,emoji:g.emoji,minutes:45,cost:"free"});details.onclick=()=>{const opening=detailBox.classList.contains("hidden");detailBox.classList.toggle("hidden");details.textContent=opening?"Hide details":"More details"};if(another)another.onclick=generate}
function generate(){let g=BNM_GAME_CHALLENGES[selected];current=g.challenges[Math.floor(Math.random()*g.challenges.length)];BNM.track("gaming_challenge",{game:selected,challenge:current.title});gamingResult.innerHTML=renderCard(current,g,false);wire(gamingResult,current,g,false)}
function random(){let a=Object.keys(BNM_GAME_CHALLENGES);selected=a[Math.floor(Math.random()*a.length)];BNM.show("gaming");draw();gamingToolbar.classList.remove("hidden");gamingAll.classList.add("hidden");generate()}
function browseAll(){if(!selected)return;let g=BNM_GAME_CHALLENGES[selected];gamingAllTitle.textContent=`All ${g.name} challenges`;gamingAllGrid.innerHTML="";g.challenges.forEach(c=>{let wrap=document.createElement("div");wrap.innerHTML=renderCard(c,g,true);const card=wrap.firstElementChild;gamingAllGrid.appendChild(card);wire(card,c,g,true)});gamingAll.classList.remove("hidden");gamingAll.scrollIntoView({behavior:"smooth",block:"start"});BNM.track("gaming_browse_all",{game:selected})}
document.addEventListener("DOMContentLoaded",()=>{const browse=document.getElementById("gamingBrowseAll"),close=document.getElementById("gamingAllClose");if(browse)browse.onclick=browseAll;if(close)close.onclick=()=>gamingAll.classList.add("hidden")});
return{open,random}})();